# Generated by Django 5.2.6 on 2025-09-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'employee_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employee_designation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('official_email', models.CharField(max_length=254, unique=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=100)),
                ('profile_pic', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_category', models.CharField(max_length=20)),
                ('user_type', models.CharField(max_length=20)),
                ('approved', models.IntegerField()),
            ],
            options={
                'db_table': 'employee_user',
                'managed': False,
            },
        ),
    ]
