# Generated by Django 5.2.6 on 2025-10-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_email', models.CharField(help_text='The email used in the login attempt.', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('auth_method', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('login_successful', models.BooleanField()),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for login failure, if any.', max_length=255, null=True)),
            ],
            options={
                'db_table': 'employee_loginlog',
                'managed': False,
            },
        ),
    ]
