# Generated by Django 5.2.6 on 2025-09-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, help_text='Personal email id', max_length=254, null=True),
        ),
    ]
